### ISSUE TITLE
improve flatJSON plugin

### ISSUE THREAD

**Issue by wenzhixin** [djhvscf/flatJSON#1]
1. Do not support flat object: http://jsfiddle.net/jb114t4h/1/
   
   > 118: if ($.isArray(options.data)) {
2. Do not support unflat: http://jsfiddle.net/jb114t4h/2/
   
   > 88: if (Object(data) !== data || Array.isArray(data)) {
3. Suggest to use methods, for example:

``` js
$.flatJSON.flat(data);
$.flatJSON.unflat(data);
```

**Comment by djhvscf** [comment]
@wenzhixin this release support the flat object : https://github.com/djhvscf/flatJSON/releases/tag/v1.3.0
